Different changes
StefanBehring/react-harry-potter-app pull request #3
Opened 2021-09-16 13:34 UTC by StefanBehring

Add show all
Removed not longer needed console logs
Deleted not longer needed files
Change height of Card to max-content
Add fetch from API functionality

2021-09-16 14:12 UTC, macfrei requested changes
Well done, please consider my comments! You can just change them locally and then push again. Afterwards you can merge this PullRequest 👍

2021-09-16 14:12 UTC, macfrei commented on src/components/app/App.js
> +      <Header onHeaderTitleClick={onNavBtnClick} />
So about this naming convention: when passing a function as prop, we tend to call it `onSomething`, when we actually call/invoke the function, we call often it `handleSomething`. 
```suggestion
      <Header onHeaderTitleClick={handleNavBtnClick} />
```

2021-09-16 14:12 UTC, macfrei commented on src/components/app/App.js
>    const onNavBtnClick = house => {
```suggestion
  const handleNavBtnClick = house => {
```

2021-09-16 14:12 UTC, macfrei commented on src/components/cards/Cards.js
> +      })
I don't think the `throw response` is necessary. 🤔 If it is not okay, then it will be caught by the `.catch` I think.
```suggestion
      .then(response => response.json())
```

2021-09-16 14:12 UTC, macfrei commented on src/components/cards/Cards.js
> +  let workingData =
Why is this declared with `let` and not `const`? Also `workingData` is not a good name. Usually, we want to name the things as they are or what they contain. In this case `characters`. Maybe here `filteredCharacters` would make more sense?
```suggestion
  const filteredCharacters =
```

2021-09-16 14:12 UTC, macfrei commented on src/components/cards/Cards.js
> +  const [dataArr, setDataArr] = useState(null)
This is a bit too generic. Please call it something else, for example `[characters, setCharacters]`

2021-09-16 14:13 UTC, macfrei commented on src/components/cards/Cards.js
> +    fetch('http://hp-api.herokuapp.com/api/characters')
Also, I think you'll need to set this URL to this:
```suggestion
    fetch('https://hp-api.herokuapp.com/api/characters')
```

2021-09-16 15:01 UTC, StefanBehring commented on src/components/cards/Cards.js
> +      })
> Within the first .then() callback, we check to see if the response was okay (response.ok). If so, we return our response to pass to the next, then call back as JSON data, since that's the data we'll get back from our random user API.
> 
> If it's not an okay response, we assume there was an error making the request. Using fetch, we need to handle the errors ourselves, so we throw response as an error for it to handled by our catch callback.
> [Source](https://www.freecodecamp.org/news/fetch-data-react/)

Tbh, I dont know. I found it on freecodecamp like this and I thought that the reason why they are using it makes sense.

2021-09-16 15:03 UTC, StefanBehring commented on src/components/app/App.js
> +      <Header onHeaderTitleClick={onNavBtnClick} />
Yeah, I changed it to: 
**navBtnClickHandler**

2021-09-16 15:08 UTC, StefanBehring commented on src/components/cards/Cards.js
> +  let workingData =
I actually had it a const before, but then I got an 'warning' for line 45 when I map it:

> workingData.map((person, i) => (...)

I changed the naming, I wasn't really happy about it from the getgo

2021-09-16 15:13 UTC, StefanBehring commented on src/components/cards/Cards.js
> +  const [dataArr, setDataArr] = useState(null)
Changed it to:

> [characters, setCharacters]

2021-09-16 15:15 UTC, StefanBehring commented on src/components/cards/Cards.js
> +    fetch('http://hp-api.herokuapp.com/api/characters')
Changed it, even so in their documentation they use the http version

2021-09-16 15:51 UTC, merged

2021-09-17 07:04 UTC, macfrei commented on src/components/cards/Cards.js
> +      })
Hm, yea, I am not an expert about best practices here as well. 😅 Just the way I learned it is the suggestion I have made, but as long as it is working, it should be okay.

2021-09-17 07:05 UTC, macfrei commented on src/components/cards/Cards.js
> +    fetch('http://hp-api.herokuapp.com/api/characters')
Yea, I know - my bad though! Should have told you guys earlier 🙈